= Red Hat OpenShift Service Mesh Advanced

In this course, students learn how to manage manage complex microservice architected applications using a service mesh.

* DURATION: 24 hours.

* MODALITY: ILT

* PROFICIENCY LEVEL: Advanced

* PRODUCT: Red Hat Service Mesh

== Description
In this course, students will build upon _Foundational_ knowledge of Red Hat OpenShift Service Mesh.
All learning objectives of this course will be achieved by applying service mesh functionality to a real-world micro-service architected application.
This course will introduce students to the use of securing inter-service communication via the mutual TLS functionality of the product.
In addition, students will utilize the _multi-tenancy_ capabilities of the product deployed on a single OpenShift cluster.
Performance testing on the service mesh _tenants_ will be conducted and results will be analyzed.
Finally, students will plugin a 3scale adapter to the _control plane_ of the Service Mesh product so as to apply API policies to both inbound traffic as well as traffic between services in the mesh.
As part of this last exercise, students will observe analytics and tracing of traffic in and throughout the service mesh.


== Agenda

Each course module listed below will consist of a slide presentation and one or more corresponding hands-on labs.

. *01_Whats_New*
.. Slides: What's New with Service Mesh (Erik Jacobs)
.. Labs
... 01_1_Multi_Tenancy_Lab (jeff)
.... Review Service Mesh operator and CRDs
.... Review Service Mesh control plane
... 01_2_Service_Mesh_MSA_Lab (jeff)
.... Introduce Emergency Response demo 
.... Add Emergency Response namespace to _ServiceMeshMemberRoll_
.... Start Emergency Response demo 
.... Envoy configuration via ADS
.. Slides: Red Hat Service Mesh Engineering Design Decisions (Kevin Connor)

. *02_Secure* 
.. Slides: Service Mesh Security (bernard)
.. Labs (bernard)
... 02_1_Vulnerable_MSA_Lab
.... Deploy man-n-middle attack
... 02_1_Secure_MSA_using_mTLS_Lab 
.... mTLS communication applied
.... Navigate to Grafana & Kiali dashboards to view encrypted connections
.... man-in-middle attack thwarted

. *03_Control*
.. Slides: ???
.. Labs:
... 03_1_Security_Policies_Lab 
... 03_2_Apply_API_Policies_Lab (jeff)
... 03_3_Onboard_API_Consumers_Lab

. *04_Connect*
.. Slides: ???
.. Labs:
... 04_1_Circuit_Breaker_Lab (jeff)
... 04_2_Dark_Launch_Lab (jeff)

. *05_Observe* 
.. Slides ???
.. Labs
... 05_1_Observe_Tracing_Lab (bernard)
... 05_2_Prometheus_AlertManager_Lab (bernard)
... 05_3_Kiali_Service_Graph_Lab (????  .... Bernard)

. *06_Production Considerations*
.. Slides: Production_Considerations_and_Load_Testing (Kevin Connor)
.. Labs:
... 06_Chaos_Engineering_Lab (bernard)

. *07_Homework*
.. 07_1_Homework_Lab  (jeff)

== Lab Environment (jeff)
. *OCP 4.2*
.. Provisioned from labs.opentlc.com -> OCP4 Workshop Deployer
.. Instructor uses _MachineSet API_ to scale to appropriately sized cluster 
... Emergency Response (16GB RAM) + Istio Control Plane (6GB RAM) = 22GB RAM per student
.. RH-SSO
... Used as Identity Provider (via OIDC) for the following:
.... OCP 4 
.... 3scale
.... Emergency Response Demo ??
.. Service Mesh Control Plane
... Instructor layers 1 Service Mesh Control Plane per student
... user[1-100] has view access to service mesh control plane
... admin[1-100] has admin access to service mesh control plane  (but is not a cluster admin)
.. 3scale Control Plane
... Insructor provisions 1 3scale Control Plane
... Instructor creates 1 tenant per student
.... user[1-100] is an API provider for their tenant
.... admin[1-100] is a admin of their tenant

.. Instructor layers 1 Emergency Response Demo per student
... Both uer[1-100] and admin[1-100] have admin access to this _emergency-response-demo_ namespace
. *Client tooling* (on student laptop)
.. Browser
.. oc 4.2 utility
.. istioctl


== Reference

. link:https://docs.google.com/document/d/1y1EYWVl6UdJiaz1p-dHjtEg-GyisokQDc7dl1wXDBDc/edit#heading=h.et0u47hb6ot1[Service Mesh Technical Competency Model]

