= Red Hat OpenShift Service Mesh Advanced

:numbered:

== Agenda

Each course module listed below will consist of a slide presentation and one or more corresponding hands-on labs.

. *01_Whats_New*
.. 01_1_Multi_Tenancy_Overview_Lab

. *02_Secure* 
.. 02_1_Mesh_Security_using_mTLS_Lab

. *03_Connect*
.. 03_1_Advanced_Mesh_Routing_Lab

. *04_Control*
.. 04_1_Apply_API_Policies_Lab
.. 05_2_Onboard_API_Consumers_Lab

. *05_Observe* 
.. 05_1_Observe_API_and_Mesh_Tracing_Lab
.. 05_2_Observe_API_and_Mesh_Analytics_Lab
.. 05_3_Debug_MSA_Application_Lab

== Reference

. link:https://docs.google.com/document/d/1y1EYWVl6UdJiaz1p-dHjtEg-GyisokQDc7dl1wXDBDc/edit#heading=h.et0u47hb6ot1[Service Mesh Technical Competency Model]

== Description
In this course, students will build upon _Foundational_ knowledge of Red Hat OpenShift Service Mesh.
All learning objectives of this course will be achieved by applying service mesh functionality to a real-world micro-service architected application.
This course will introduce students to the use of securing inter-service communication via the mutual TLS functionality of the product.
In addition, students will utilize the _multi-tenancy_ capabilities of the product deployed on a single OpenShift cluster.
Performance testing on the service mesh _tenants_ will be conducted and results will be analyzed.
Finally, students will plugin a 3scale adapter to the _control plane_ of the Service Mesh product so as to apply API policies to both inbound traffic as well as traffic between services in the mesh.
As part of this last exercise, students will observe analytics and tracing of traffic in and throughout the service mesh.
