apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: global-istio-system

# Documentation: https://servicemesh--ocpdocs.netlify.com/openshift-enterprise/latest/service_mesh/service_mesh_install/installing-ossm.html#ossm-cr-parameters_installing-ossm

spec:
  istio:

    istio_cni:
      enabled: false

    kiali:
      enabled: false

    mixer:
      enabled: false

    threeScale:
      enabled: false

    tracing:
      # The Jaeger agent runs as a DaemonSet, therefore tracing may only be enabled for a single ServiceMeshControlPlane instance. 
      enabled: true
      jaeger:
        tag: 1.13.1
        hub: registry.redhat.io/distributed-tracing-tech-preview
        template: all-in-one
        agentStrategy: DaemonSet

