:noaudio:
:scrollbar:
:toc2:
:linkattrs:
:data-uri:

= Lab Assets Overview

.Goals
* Overview of student lab environment
* Overview of Red Hat Service Mesh operator
* Overview of Red Hat Service Mesh _control plane_
* Introduction to Emergency Response demo

:numbered:

== OpenShift
Your student lab is built on a shared OpenShift v4 cluster in the cloud.

. Have your instructor share with you the link:https://docs.google.com/spreadsheets/d/1vazinjjbOSN-uDY8u_mmg-lXtrRlZtm1l5vJQucdKz8/edit#gid=959461386[details of your lab environment].
. Open a terminal window on your local machine and download the script that sets needed environment variables for the labs in this course:

+
-----
curl https://raw.githubusercontent.com/gpe-mw-ansible-org/ocp_service_mesh_advanced/master/utils/set_env_vars.sh \
    -o /tmp/set_env_vars.sh && \
    chmod 775 /tmp/set_env_vars.sh
-----

. Using your favorite text editor, modify the variables as discussed in that shell script you previously downloaded.
. Execute the shell script so that the environment variables are applied to your existing shell:
+
-----
./tmp/set_env_vars.sh
-----

. You are provided with two different OpenShift users:

.. *$OCP_USER*
+
This user is an admin of your microservice architected business application.
This user has view access to a variety of other namespaces.


... At the terminal, authenticate into OpenShift using the user: $OCP_USER
+
-----
oc login $LAB_MASTER_API -u $OCP_USER -p $OCP_PASSWD
-----

... View a listing of OpenShift projects that you have access to:
+
-----
oc get projects
-----

.... You should see a listing similar to the following:
+
-----

istio-operator       Service Mesh Operator         Active
kafka-operator-erd                                 Active
openshift-console                                  Active
tools-erd                                          Active
user5-er-demo                                      Active
admin5-istio-system   admin5 Service Mesh System   Active
-----
+
In subsequent sections of this lab, you will be introduced to each of these namespaces.

.. *$OCP_ADMIN*
+
This user is an admin of your service mesh _control plane_.
This user has view access to a variety of other namespaces.


... At the terminal, authenticate into OpenShift using the user: $OCP_ADMIN
+
-----
oc login $LAB_MASTER_API -u $OCP_ADMIN -p $OCP_PASSWD
-----

... View a listing of OpenShift projects that you have access to:
+
-----
oc get projects
-----

.... You should see a listing similar to the following:
+
-----

istio-operator       Service Mesh Operator         Active
-----

. OpenShift Web Console:
.. At the terminal, determine the URL of the OpenShift Console:
+
-----
oc whoami --show-console
-----

.. Open a browser tab and navigate to the URL determined in the previous step.
.. Authenticate using the values of $OCP_USER and $OCP_PASSWD

== Red Hat Service Mesh Operator & CRDs

. View the previously installed Service Mesh operator:
+
-----
oc get pods -n istio-operator

istio-node-8lmjb                1/1     Running   0          15h
istio-node-q625x                1/1     Running   0          15h
istio-node-r26x7                1/1     Running   0          15h
istio-node-tpvbx                1/1     Running   0          15h
istio-node-w2fhr                1/1     Running   0          15h
istio-operator-7fdc886f-t4vw2   1/1     Running   0          15h
-----
+
This operator is global (to the OpenShift cluster) in scope.
+
TO-DO:  Elaborate on each of the above

. View the Service Mesh related _custom resource definitions_ that extend the OpenShift master API:
+
-----
oc get crd --as=system:admin | grep 'maistra\|istio'
-----
+
TO-DO:  Highlight some of the more important CRDs

== Red Hat Service Mesh Control Plane

== Emergency Response Demo



ifdef::showscript[]
-----


-----
endif::showscript[]