:noaudio:
:scrollbar:
:toc2:
:linkattrs:
:data-uri:

= Service Mesh Multi Tenancy Lab

.Goals
** Understand ServiceMeshMemberRoll
** Understand Envoy _Data Plane_

:numbered:

== ServiceMeshMemberRoll

. Switch to your service mesh control plane administrator user:
+
-----
oc login -u $SM_CP_ADMIN
-----

-----
echo "apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
spec:
  members:
  - $ERDEMO_USER-er-demo" | oc apply -f -
-----

. Notice that your $ERDEMO_USER-er-demo namespace now includes _kiali_ and _maistra_ annotations:
+
-----
echo -en "\n\n$(oc get project $ERDEMO_USER-er-demo -o template --template='{{.metadata.labels}}')\n"


map[kiali.io/member-of:admin50-istio-system maistra.io/member-of:admin50-istio-system]
-----

== Opt-in Auto-Injection Annotations

When deploying an application into the Red Hat OpenShift Service Mesh you must opt in to injection by specifying the sidecar.istio.io/inject annotation with a value of "true". 

Opting in ensures that the sidecar injection does not interfere with other OpenShift features such as builder pods used by numerous frameworks within the OpenShift ecosystem.

In this section of this lab you (as the owner of the Emergency Response application) opt in a selective list of services for auto injection of a sidecar.

. Switch to the $ERDEMO_USER:
+
-----
oc login -u $ERDEMO_USER
-----
+
The $ERDEMO_USER is the admin of the $ERDEMO_USER-er-demo namespace where the Emergency Response application resides.

. Review the contents of link:https://github.com/gpe-mw-training/ocp_service_mesh_advanced/blob/master/utils/inject_istio_annotation.sh[this script].


. Execute script that adds Envoy auto-injection annotations to Emergency Response services:
+
-----
curl https://raw.githubusercontent.com/gpe-mw-ansible-org/ocp_service_mesh_advanced/master/utils/inject_istio_annotation.sh \
    -o /tmp/set_env_vars.sh && \
    chmod 775 /tmp/inject_istio_annotation.sh && \
    /tmp/inject_istio_annotation.sh
------

. After completion of the script, review the list Emergency Response related pods:
+
-----
oc get pods -l group=erd-services

user50-disaster-simulator-1-p9gfl          2/2     Running   7          9h
user50-incident-priority-service-1-hgmdn   2/2     Running   4          9h
user50-incident-service-1-sz4dk            2/2     Running   3          9h
user50-mission-service-1-jz2r8             2/2     Running   9          9h
user50-process-service-4-cz5sz             2/2     Running   5          7h17m
user50-responder-service-1-qm5gn           2/2     Running   3          7h14m
user50-responder-simulator-1-tdrz2         2/2     Running   6          7h13m
-----

.. Notice that each of these pods indicates that two containers have started.
.. You could use a script such as the following to identify a list of container names for each of the pods:
+
-----
for POD_NAME in $(oc get pods -l group=erd-services -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}')
do
    oc get pod $POD_NAME  -o jsonpath='{.metadata.name}{"    :\t\t"}{.spec.containers[*].name}{"\n"}'
done


user50-disaster-simulator-1-p9gfl    :          user50-disaster-simulator istio-proxy
user50-incident-priority-service-1-hgmdn    :           user50-incident-priority-service istio-proxy
user50-incident-service-1-sz4dk    :            user50-incident-service istio-proxy
user50-mission-service-1-jz2r8    :             user50-mission-service istio-proxy
user50-process-service-4-cz5sz    :             user50-process-service istio-proxy
user50-responder-service-1-qm5gn    :           user50-responder-service istio-proxy
user50-responder-simulator-1-tdrz2    :         user50-responder-simulator istio-proxy
-----
+
Notice that the output indicates the existence of an _istio-proxy_ container co-located with the primary business service containers for each pod.

.. The two databases leveraged by the Emergency Response demo ( _postgresql_ and _user50-process-service-postgresql_ ) are also now injected with an envoy proxy.
+
Verify that this is infact the case either through the OpenShift web console or the oc utility.

== Envoy _Data Plane_

. Capture the details of the _istio-proxy_ container from the _responser-service_ pod:
+
-----
oc get pod \
       $(oc get pod -l group=erd-services -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}' | grep responder-service) \
       -o json \
       | jq .spec.containers[1] \
        > /tmp/responser_envoy.json
-----

. Study the details of the _istio-proxy_ container:
+
-----
less /tmp/responder_envoy.json
-----

. Answer the following questions pertaining to this _istio-proxy_ container:
+
TO_DO

== Getting Started with the Emergency Response demo

-----
echo -en "\n\n$(oc get route $ERDEMO_USER-emergency-console -o --template={{.spec.host}}  -n  $ERDEMO_USER-er-demo)\n"
-----

link:https://www.erdemo.io/gettingstarted/[Getting Started]

